// Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/ptlist": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Returns all matching timestamps of a periodic task between 2 points in time.",
                "parameters": [
                    {
                        "type": "string",
                        "example": "1y,1mo,1d,1h",
                        "description": "Period",
                        "name": "period",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "America/Los_Angeles",
                        "description": "Timezone",
                        "name": "tz",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "20060102T150405Z",
                        "description": "Start point",
                        "name": "t1",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "20060102T150405Z",
                        "description": "End point",
                        "name": "t2",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Periodic Task Api",
	Description:      "JSON/HTTP service in Golang, that returns the matching timestamps of a periodic task.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
